config/routes.rb
Rainforest::Application.routes.draw do

  resources :products do 
    resources :reviews
  end
  
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :name, :price_in_cents, :price_in_dollars

  validates :description, :name, :presence => true
  validates :price_in_cents, :numericality => {:only_integer => true}
  validates :price_in_dollars, :numericality => true

  has_many :reviews

  def price_in_dollars
  	if self.price_in_cents?
  		self.price_in_cents.to_f / 100 
  	end
  end

  def price_in_dollars=(amount)
  	if amount.present?
  	self.price_in_cents = (amount.to_f * 100).to_i
  	end
	end

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
  attr_accessible :comment, :product_id, :user_id, :user, :product

  validates :comment, :product, :user, :presence => true

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation 
  
  has_secure_password

  validates_presence_of :password, :on => :create
  validates :name, :presence => true
  validates :email, :presence => true, :uniqueness => true

  has_many :reviews

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

   def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  def index
    @products = Product.all
  end

  # GET /products/1
  def show
    @review = Review.new
    @product = Product.find(params[:id])
  end

  # GET /products/new
  def new
    @review = Review.new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  def create
    @product = Product.new(params[:product])
    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render action: "new" 
    end
  end

  # PUT /products/1
  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(params[:product])
      redirect_to @product, notice: 'Product was successfully updated.' 
    else
      render action: "edit"    
    end
  end

  # DELETE /products/1  
  def destroy
    @product = Product.find(params[:id])
    @product.destroy    
    redirect_to products_url
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :load_product


  # GET /product/:id/reviews
 
  def index
    @reviews = Review.all
  
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
    @review = Review.find(params[:id])

  
  end

  # GET /reviews/new
  # GET /reviews/new.json
  def new
    @review = Review.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @review }
    end
  end

  # GET /reviews/1/edit
  def edit
    @review = Review.find(params[:id])
  end

  # POST /product/:id/reviews
  def create
    # @review = Review.new(
    #   :comment => params[:review][:comment], 
    #   :product_id => @product.id, 
    #   :user_id => current_user.id
    #   )
    @review = @product.reviews.build(
      :comment => params[:review][:comment],
      :user_id => current_user.id
      )

      if @review.save
        redirect_to @product, notice: 'Review was successfully created.'
      else
        render "/products/show"
      end
  end

  # PUT /reviews/1
  # PUT /reviews/1.json
  def update
    @review = Review.find(params[:id])

    respond_to do |format|
      if @review.update_attributes(params[:review])
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review = Review.find(params[:id])
    @review.destroy

    respond_to do |format|
      format.html { redirect_to reviews_url }
      format.json { head :no_content }
    end
  end

  def load_product
    @product = Product.find(params[:product_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by_email(params[:email])
		if user && user.authenticate(params[:password])
    session[:user_id] = user.id
    redirect_to products_path, :notice => "Logged in!"
  	else
    flash.now[:alert] = "Invalid email or password"
    render "new"
  	end
	end
	

	def destroy
		session[:user_id] = nil
    redirect_to products_path, :notice => "Logged out!"
	end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create 
		@user = User.new(params[:user])
		if @user.save
			# flash[:notice]
			# flash[:alert]
			# flash[:error]
			flash[:notice] = "Signup was successful"
			redirect_to products_path
		else
			render :action => :new
		end

	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper

	def product_price(product)
		number_to_currency product.price_in_dollars
	end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rainforest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

	<p class="userinfo">
		<% if current_user %>
			Signed in as <%= current_user.email %>.
			<%= link_to "Log-out", session_path(current_user), :method => :delete %> 
		<% else %>
			<%= link_to "Log-in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
		<% end %>
	</p>
</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price_in_dollars %><br />
    <%= f.text_field :price_in_dollars %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_reviews.html.erb
<h3>Reviews</h3>

<p> Reviews for <%= @product.name %></p>

<% @product.reviews.each do |review| %>
	<p>
		<%= review.comment %>
		<br>
		<em> by <%= review.user.name %></em>
		Added on: <%= review.created_at %>
	</p>
	<% end %>


<h4>New Review</h4>

<% if current_user %>
	<%= render "reviews/form" %>
<% else %>
	<p>Please <%= link_to "Log-in", 
		new_session_path %> to add a review.</p>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<%= flash[:notice] %>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Price in cents</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.description %></td>
    <td><%= product.price_in_cents %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Description:</b>
  <%= @product.description %>
</p>

<p>
  <b>Price in dollars:</b>
  <%= product_price(@product) %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

<%= render :partial => "/products/reviews" %>

app/views/reviews/_form.html.erb
<%= form_for([@product, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<h1>Listing reviews</h1>

<table>
  <tr>
    <th>User</th>
    <th>Product</th>
    <th>Comment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reviews.each do |review| %>
  <tr>
    <td><%= review.user %></td>
    <td><%= review.product %></td>
    <td><%= review.comment %></td>
    <td><%= link_to 'Show', product_review_path(review.product, review) %></td>
    <td><%= link_to 'Edit', edit_product_review_path(review.product, review) %></td>
    <td><%= link_to 'Destroy', product_review_path(review.product, review), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

# <%= link_to 'New Review', new_product_review_path(@product) %>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @review.user %>
</p>

<p>
  <b>Product:</b>
  <%= @review.product %>
</p>

<p>
  <b>Comment:</b>
  <%= @review.comment %>
</p>


<%= link_to 'Edit', edit_review_path(@review) %> 
<%= link_to 'Back', reviews_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages" id="error_explanation">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><% if message == "Password digest can't be blank"%>
          	<%= "Password can't be blank" %>
          	<% else %>
          	<%= message %>
          	<% end %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

 <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
	</div>
  <div class="actions">
    <%= f.submit %>
	</div>
<% end %>